#!/usr/bin/env python3
"""Extract the fixed RAM variable addresses from the (C-preprocessed) GBA
linker script and emit an implicit GNU ld script containing absolute symbol
assignments.

The decomp does not define its RAM variables in C; every global lives at a
fixed EWRAM/IWRAM address chosen by linker.ld. The PC port maps the GBA
memory regions at their real addresses (see port/src/memory.c), so the same
addresses can be reused as-is.

Usage: gen_ram_syms.py preprocessed_linker.ld out.ld [--exclude name]... [--prefix _]
"""
import re
import sys

# ram_* symbols that are data tables (copied from ROM to IWRAM) rather than code
RAM_DATA = {'ram_gUnk_080B2A70', 'ram_0x80b2b58', 'ram_0x80b2bd8', 'ram_0x80b2be8'}
BASES = {'ewram': 0x02000000, 'iwram': 0x03000000}
SECTION = re.compile(r'^\s*(ewram|iwram)\s*\(NOLOAD\)')
ASSIGN = re.compile(r'\.\s*=\s*(0x[0-9A-Fa-f]+)\s*;\s*([A-Za-z_]\w*)\s*=\s*\.\s*;')
TOP = re.compile(r'^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*;')


def main():
    src, dst = sys.argv[1], sys.argv[2]
    exclude = set()
    prefix = ''
    args = sys.argv[3:]
    while args:
        a = args.pop(0)
        if a == '--exclude':
            exclude.add(args.pop(0))
        elif a == '--prefix':
            # Windows (PE/COFF) C symbols carry a leading underscore
            prefix = args.pop(0)
    out = ['/* generated by port/tools/gen_ram_syms.py - do not edit */']
    section = None
    depth = 0
    for line in open(src):
        m = SECTION.match(line)
        if m:
            section = m.group(1)
            continue
        if section is None:
            t = TOP.match(line)
            if t and t.group(1) not in exclude:
                out.append('%s%s = %s;' % (prefix, t.group(1), t.group(2)))
            continue
        if line.strip().startswith('}'):
            section = None
            continue
        for off, name in ASSIGN.findall(line):
            # ram_* are addresses of ARM routines copied to IWRAM on hardware;
            # the PC port implements those in C.
            if (name.startswith('ram_') and name not in RAM_DATA) or name in exclude:
                continue
            out.append('%s%s = 0x%08X;' % (prefix, name, BASES[section] + int(off, 16)))
    with open(dst, 'w') as f:
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
