#!/usr/bin/env python3
"""
Turns the asset layout (see make_asset_layout.py) into assembly.

For every data object of the game one .s file is written with the same
sections, sizes, symbols and pointers as the real data, but zeros instead of
the content. rom_table.s describes the game data as named entries, one per
section: where the section is, and which runs of it come from where in the
ROM. port/src/resources.c uses it to build the resource pack from the ROM and
to copy the pack's content into place at startup.

usage: gen_asset_skeleton.py LAYOUT.json.gz OUT_DIR
Writes OUT_DIR/<object>.s for every object, OUT_DIR/rom_table.s and OUT_DIR/objects.txt.
"""
import gzip
import json
import zlib
import os
import sys


def emit_section(out, sec, label, sec_labels):
    out.append("\t.section %s" % sec["name"])
    out.append("\t.balign %d" % sec["align"])
    out.append("%s:" % label)
    events = []  # (offset, order, text)
    for name, off, is_global in sec["symbols"]:
        if is_global:
            events.append((off, 0, "\t.global %s" % name))
        events.append((off, 1, "%s:" % name))
    for off, target, addend in sec["relocs"]:
        if target[0] == "section":
            ref = sec_labels[target[1]]
        else:
            ref = target[1]
        events.append((off, 2, "\t.4byte %s%+d" % (ref, addend), 4))
    label_offsets = sorted({off for _, off, _ in sec["symbols"]})
    for off, hexbytes in sec["literal"]:
        data = bytes.fromhex(hexbytes)
        # split at labels so that every label lands on its offset
        cuts = [off] + [l for l in label_offsets if off < l < off + len(data)] + [off + len(data)]
        for a, b in zip(cuts, cuts[1:]):
            chunk = data[a - off:b - off]
            events.append((a, 2, "\t.byte " + ",".join(str(x) for x in chunk), len(chunk)))
    events.sort(key=lambda e: (e[0], e[1]))
    pos = 0
    for ev in events:
        off = ev[0]
        if off > pos:
            out.append("\t.skip %d" % (off - pos))
            pos = off
        out.append(ev[2])
        if len(ev) > 3:
            pos += ev[3]
    if sec["size"] > pos:
        out.append("\t.skip %d" % (sec["size"] - pos))


def main():
    layout_path, out_dir = sys.argv[1:3]
    layout = json.load(gzip.open(layout_path, "rt"))
    entries = []  # (name, label, size, first run, run count)
    runs = []
    names = []
    for i, obj in enumerate(layout["objects"]):
        base = os.path.splitext(obj["name"])[0]
        out = ["/* generated by gen_asset_skeleton.py from the asset layout, do not edit */"]
        for name, value in obj["abs"]:
            out.append("\t.global %s" % name)
            out.append("\t.set %s, %d" % (name, value))
        sec_labels = {sec["index"]: "__tmc_sk%d_%d" % (i, sec["index"]) for sec in obj["sections"]}
        for sec in obj["sections"]:
            label = sec_labels[sec["index"]]
            emit_section(out, sec, label, sec_labels)
            if sec["runs"]:
                out.append("\t.global %s" % label)
                entries.append((base + ":" + sec["name"], label, sec["size"], len(runs), len(sec["runs"])))
                for off, n, rom in sec["runs"]:
                    runs.append("\t.4byte %d, %d, %d" % (off, rom, n))
        path = os.path.join(out_dir, base + ".s")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        text = "\n".join(out) + "\n"
        if not os.path.exists(path) or open(path).read() != text:
            open(path, "w").write(text)
        names.append(base)

    layout_hash = zlib.crc32(gzip.open(layout_path, "rb").read())
    rt = ["/* generated by gen_asset_skeleton.py, do not edit */",
          "\t.section .rodata",
          "\t.balign 4",
          "\t.global gPortDataEntries",
          "gPortDataEntries:"]
    for i, (name, label, size, first, count) in enumerate(entries):
        rt.append("\t.4byte __tmc_name%d, %s, %d, %d, %d" % (i, label, size, first, count))
    rt += ["\t.global gPortDataRuns", "gPortDataRuns:"] + runs
    rt += ["\t.global gPortDataEntryCount", "gPortDataEntryCount:", "\t.4byte %d" % len(entries),
           "\t.global gPortDataLayoutHash", "gPortDataLayoutHash:", "\t.4byte %d" % layout_hash,
           "\t.global gPortRomSize", "gPortRomSize:", "\t.4byte %d" % layout["rom_size"]]
    for i, (name, _, _, _, _) in enumerate(entries):
        rt.append('__tmc_name%d: .asciz "%s"' % (i, name))
    text = "\n".join(rt) + "\n"
    path = os.path.join(out_dir, "rom_table.s")
    if not os.path.exists(path) or open(path).read() != text:
        open(path, "w").write(text)
    text = "\n".join(names) + "\n"
    path = os.path.join(out_dir, "objects.txt")
    if not os.path.exists(path) or open(path).read() != text:
        open(path, "w").write(text)


if __name__ == "__main__":
    main()
